# get an account by id
GET http://127.0.0.1:8080/account/0

###

# deposit specified amount into the account
PUT http://127.0.0.1:8080/account/deposit
Content-Type: application/json

{
  "id": "0",
  "amount": "1.75",
  "currencyName": "RUB"
}

###

# withdraw specified amount from the account
PUT http://127.0.0.1:8080/account/withdraw
Content-Type: application/json

{
  "id": "0",
  "amount": "5.75",
  "currencyName": "RUB"
}

###
