# get all currencies ever create
GET http://127.0.0.1:8080/currencies

###

# get a particular currency
GET http://127.0.0.1:8080/currency/RUB

###

# create a currency
POST http://127.0.0.1:8080/currency
Content-Type: application/json

{
  "name": "RUB",
  "exchangeRate": "1.65"
}

###

# update exchange rate of a currency
PUT http://127.0.0.1:8080/currency
Content-Type: application/json

{
  "name": "RUB",
  "exchangeRate": "1.75"
}

###

# delete a currency. Not supported.
#DELETE http://127.0.0.1:8080/currency/RUB

###
