# get a user
GET http://127.0.0.1:8080/user/0

###

# create a user
POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "fullName": "Abduqodiri Qurbonzoda"
}

###

# rename a user
PUT http://127.0.0.1:8080/user/0
Content-Type: application/json

{
  "newFullName": "Nikita Nozhkin"
}

###

# delete a user
DELETE http://127.0.0.1:8080/user/0

###

# create an account for the user
POST http://127.0.0.1:8080/user/0/account
Content-Type: application/json

{
  "currencyName":  "RUB"
}

###

# delete an account of the user
DELETE http://127.0.0.1:8080/user/0/account/0

###