GET http://127.0.0.1:8080/user/0

###

POST http://127.0.0.1:8080/user
Content-Type: application/json

{
  "fullName": "Abduqodiri Qurbonzoda"
}

###

PUT http://127.0.0.1:8080/user/0
Content-Type: application/json

{
  "newFullName": "Nikita Nozhkin"
}

###

DELETE http://127.0.0.1:8080/user/0

###

POST http://127.0.0.1:8080/user/0/account
Content-Type: application/json

{
  "currencyName":  "RUB"
}

###

DELETE http://127.0.0.1:8080/user/0/account/0

###